name: Build Archer A6 VLESS Minimal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.5/targets/ath79/generic/openwrt-imagebuilder-23.05.5-ath79-generic.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-23.05.5-ath79-generic.Linux-x86_64.tar.xz

      - name: Prepare files
        run: |
          mkdir -p files/usr/bin

          wget https://github.com/XTLS/Xray-core/releases/download/v25.7.26/Xray-linux-mips32-v5.zip

          unzip Xray-linux-mips32-v5.zip

          cp xray files/usr/bin/xray
          chmod 755 files/usr/bin/xray

      - name: Build
        run: |
          cd openwrt-imagebuilder-23.05.5-ath79-generic.Linux-x86_64

          make image \
          PROFILE="tplink_archer-c6-v2" \
          PACKAGES="pbr kmod-tun iptables-nft ca-bundle" \
          FILES="../files"

      - name: Find firmware
        run: |
          find . -name "*sysupgrade.bin"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Archer-A6-VLESS
          path: |
            **/*sysupgrade.bin
