name: Check OpenWrt Profiles

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:

      - name: Download ImageBuilder
        run: |
          wget https://downloads.openwrt.org/releases/23.05.5/targets/ath79/generic/openwrt-imagebuilder-23.05.5-ath79-generic.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-23.05.5-ath79-generic.Linux-x86_64.tar.xz

      - name: Show profiles
        run: |
          cd openwrt-imagebuilder-23.05.5-ath79-generic.Linux-x86_64
          make info | grep -i "archer"
