name: Check Xray

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:

      - name: Download Xray release
        run: |
          wget -qO- https://api.github.com/repos/XTLS/Xray-core/releases/latest | grep browser_download_url
